---
# required directory | blackbox_exporter_conf
- name: required directory | blackbox_exporter_conf
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - "{{ blackbox_exporter_conf_required_directory }}"
  when: blackbox_exporter_conf_required_directory is defined
