---
# check distribution exist | alertmanager
- name: check distribution exist | alertmanager
  local_action: stat path="{{ role_path }}/tasks/distribution/{{ distribution }}/main.yml"
  register: distribution_path_stat

# set variables | alertmanager
- name: set variables | alertmanager
  set_fact:
    distribution_yml_path: "{{ role_path }}/tasks/distribution/{{ distribution }}/main.yml"
  when: distribution_path_stat.stat.exists == True

# include tasks distribution if exist | alertmanager
- include_tasks: "{{ distribution_yml_path | default(role_path + '/tasks/common/empty.yml') }}"
