---
# required directory | alertmanager
- name: required directory | alertmanager
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - "{{ alertmanager_required_directory }}"
  when: alertmanager_required_directory is defined
