---
# cleanup | local | prometheus
- name: cleanup | local | prometheus
  become: True
  become_user: root
  become_method: sudo
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ prometheus_cleanup_local }}"
  when: prometheus_cleanup_local is defined
  run_once: true
  delegate_to: localhost

# cleanup | remote | prometheus
- name: cleanup | remote | prometheus
  become: True
  become_user: root
  become_method: sudo
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ prometheus_cleanup_remote }}"
  when: prometheus_cleanup_remote is defined
