---
redis_exporter_service:
- name: redis_exporter
  daemon_reload: yes

redis_exporter_required_directory:
- path: /data
  owner: root
  group: root
  mode: "0755"
- path: /data/redis_exporter
  owner: redis_exporter
  group: redis_exporter
  mode: "0755"

redis_exporter_required_data_before_download_local:
- url: "https://github.com/oliver006/redis_exporter/releases/download/v1.6.1/redis_exporter-v1.6.1.linux-amd64.tar.gz"
  dest: "{{ role_path }}/files/redis_exporter-v1.6.1.linux-amd64.tar.gz"

redis_exporter_required_data:
- src: "{{ role_path }}/files/redis_exporter-v1.6.1.linux-amd64.tar.gz"
  dest: "/tmp/redis_exporter-v1.6.1.linux-amd64.tar.gz"
  owner: root
  group: root
  mode: "0644"

redis_exporter_required_data_after_template:
- src: "centos_7_x/redis_exporter.service.j2"
  dest: "/etc/systemd/system/redis_exporter.service"
  owner: root
  group: root
  mode: "0644"

redis_exporter_unarchive_data:
- src: /tmp/redis_exporter-v1.6.1.linux-amd64.tar.gz
  dest: /data/redis_exporter
  owner: redis_exporter
  group: redis_exporter
  extra_opts:
    - "--strip-components=1"
  remote_src: "yes"

# cleanup
redis_exporter_cleanup_local:
- path: "{{ role_path }}/files/redis_exporter-v1.6.1.linux-amd64.tar.gz"

redis_exporter_cleanup_remote:
- path: /tmp/redis_exporter-v1.6.1.linux-amd64.tar.gz

# environment
redis_exporter_environment:
  user: redis_exporter
  group: redis_exporter
  binary: /data/redis_exporter/redis_exporter
