---
# update conf | template | alertmanager_conf
- name: update conf | template | alertmanager_conf
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ alertmanager_conf }}"
  when: alertmanager_conf is defined
  notify:
    - restart alertmanager

# update conf | custom | alertmanager_conf
- name: update conf | custom | alertmanager_conf
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ alertmanager_conf_custom }}"
  when: alertmanager_conf_custom is defined
  notify:
    - restart alertmanager
