---
mongodb_conf_required_directory:
- path: /data
  owner: root
  group: root
  mode: "0755"
- path: /data/mongodb/log
  owner: mongod
  group: mongod
  mode: "0755"
- path: /data/mongodb/data
  owner: mongod
  group: mongod
  mode: "0755"
- path: /data/mongodb/pid
  owner: mongod
  group: mongod
  mode: "0755"
- path: /data/mongodb/conf
  owner: mongod
  group: mongod
  mode: "0755"
- path: /data/mongodb/auth
  owner: mongod
  group: mongod
  mode: "0755"
