---
- name: update firewalld
  firewalld:
    zone: "{{ item.zone | default('public') }}"
    port: "{{ item.port }}"
    permanent: "{{ item.permanent | default('yes') }}"
    state: "{{ item.state | default('enabled') }}"
  with_items:
    - "{{ firewalld_port_rules }}"
  when: firewalld_port_rules is defined
  notify:
    - firewalld reload
