---
# required directory | prometheus_conf
- name: required directory | prometheus_conf
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - "{{ prometheus_conf_required_directory }}"
  when: prometheus_conf_required_directory is defined
