---
# update conf | template | prometheus_conf
- name: update conf | template | prometheus_conf
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ prometheus_conf }}"
  when: prometheus_conf is defined
  notify:
    - restart prometheus

# update conf | custom | prometheus_conf
- name: update conf | custom | prometheus_conf
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ prometheus_conf_custom }}"
  when: prometheus_conf_custom is defined
  notify:
    - restart prometheus
