---
- name: required package | kafka
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - "{{ kafka_required_package }}"
  when: kafka_required_package is defined
