---
# required directory | redis_exporter
- name: required directory | redis_exporter
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - "{{ redis_exporter_required_directory }}"
  when: redis_exporter_required_directory is defined
