---
- name: unarchive data | redis_exporter
  unarchive:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default(omit) }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    extra_opts:
      "{{ item.extra_opts }}"
    remote_src: "{{ item.remote_src | default('yes') }}"
  with_items:
    - "{{ redis_exporter_unarchive_data }}"
  when:
    redis_exporter_unarchive_data is defined
