---
- name: required package | redis_exporter
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - "{{ redis_exporter_required_package }}"
  when: redis_exporter_required_package is defined
