---
# check vars yml exist | consul_template
- name: check vars yml exist | consul_template
  local_action: stat path="{{ role_path }}/vars/{{ distribution }}/main.yml"
  register: vars_yml

# include vars yml if exist | consul_template
- include_vars: "{{ role_path }}/vars/{{ distribution }}/main.yml"
  when: vars_yml.stat.exists == True
