---
# required directory | consul_conf
- name: required directory | consul_conf
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - "{{ consul_conf_required_directory }}"
  when: consul_conf_required_directory is defined
