---
# update conf | template | consul_template_conf
- name: update conf | template | consul_template_conf
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ consul_template_conf }}"
  when: consul_template_conf is defined
  # notify:
  #   - systemd daemon-reload
  #   - reload consul-template

# update conf | custom | consul_template_conf
- name: update conf | custom | consul_template_conf
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ consul_template_conf_custom }}"
  when: consul_template_conf_custom is defined
  # notify:
  #   - systemd daemon-reload
  #   - reload consul-template
