---
# required data | mongodb
- name: required data | mongodb
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ mongodb_required_data }}"
  when: mongodb_required_data is defined

# required data | template | mongodb
- name: required data | template | mongodb
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ mongodb_required_data_template }}"
  when: mongodb_required_data_template is defined
