---
# required directory | mongodb
- name: required directory | mongodb
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - "{{ mongodb_required_directory }}"
  when: mongodb_required_directory is defined
