---
# update sysctl | mongodb
- name: update sysctl | mongodb
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: "{{ item.sysctl_set }}"
    sysctl_file: "{{ item.sysctl_file }}"
    state: "{{ item.state }}"
    reload: "{{ item.reload }}"
  with_items:
    - "{{ mongodb_sysctl_conf }}"
  when: mongodb_sysctl_conf is defined
