---
- name: permission | after | mongodb_conf
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode | default('u=rwX,g=rX,o=rX') }}"
    recurse: "{{ item.recurse | default('no') }}"
  with_items:
    - "{{ mongodb_conf_permission_after }}"
  when: mongodb_conf_permission_after is defined
  tags:
    - initial
    - config
