---
# required data | mongodb_conf
- name: required data | mongodb_conf
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ mongodb_conf_required_data }}"
  when: mongodb_conf_required_data is defined
  tags:
    - initial
    - config

# required data | template | mongodb_conf
- name: required data | template | mongodb_conf
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ mongodb_conf_required_data_template }}"
  when: mongodb_conf_required_data_template is defined
  tags:
    - initial
    - config
