---
# update sysctl | mongodb_conf
- name: update sysctl | mongodb_conf
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: "{{ item.sysctl_set }}"
    sysctl_file: "{{ item.sysctl_file }}"
    state: "{{ item.state }}"
    reload: "{{ item.reload }}"
  with_items:
    - "{{ mongodb_conf_sysctl_conf }}"
  when: mongodb_conf_sysctl_conf is defined
  tags:
    - initial
    - config
