---
# update security limit | mongodb_conf
- name: update security limit | mongodb_conf
  pam_limits:
    domain: "{{ item.domain }}"
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
    dest: "{{ item.dest }}"
  with_items:
    - "{{ mongodb_conf_security_limit }}"
  when: mongodb_conf_security_limit is defined
  tags:
    - initial
    - config
