---
- name: required package | consul_template
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - "{{ consul_template_required_package }}"
  when: consul_template_required_package is defined
