---
# required data | blackbox_exporter
- name: required data | blackbox_exporter
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ blackbox_exporter_required_data }}"
  when: blackbox_exporter_required_data is defined

# required data | template | blackbox_exporter
- name: required data | template | blackbox_exporter
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ blackbox_exporter_required_data_template }}"
  when: blackbox_exporter_required_data_template is defined
