---
# cleanup | local | zookeeper
- name: cleanup | local | zookeeper
  become: True
  become_user: root
  become_method: sudo
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ zookeeper_cleanup_local }}"
  when: zookeeper_cleanup_local is defined
  run_once: true
  delegate_to: localhost

# cleanup | remote | zookeeper
- name: cleanup | remote | zookeeper
  become: True
  become_user: root
  become_method: sudo
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ zookeeper_cleanup_remote }}"
  when: zookeeper_cleanup_remote is defined
