---
# required directory | zookeeper
- name: required directory | zookeeper
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - "{{ zookeeper_required_directory }}"
  when: zookeeper_required_directory is defined
