---
# required data | zookeeper
- name: required data | zookeeper
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ zookeeper_required_data }}"
  when: zookeeper_required_data is defined

# required data | template | zookeeper
- name: required data | template | zookeeper
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ zookeeper_required_data_template }}"
  when: zookeeper_required_data_template is defined
