---
# update sysctl | zookeeper
- name: update sysctl | zookeeper
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: "{{ item.sysctl_set }}"
    sysctl_file: "{{ item.sysctl_file }}"
    state: "{{ item.state }}"
    reload: "{{ item.reload }}"
  with_items:
    - "{{ zookeeper_sysctl_conf }}"
  when: zookeeper_sysctl_conf is defined
