---
# required directory | consul
- name: required directory | consul
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - "{{ consul_required_directory }}"
  when: consul_required_directory is defined
