---
# required data | before | download | local | consul
- name: required data | before | download | local | consul
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items:
    - "{{ consul_required_data_before_download_local }}"
  run_once: True
  delegate_to: localhost
  when: consul_required_data_before_download_local is defined

# required data | remote | download | remote | consul
- name: required data | remote | download | remote | consul
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items:
    - "{{ consul_required_data_remote_download_remote }}"
  when: consul_required_data_remote_download_remote is defined
