---
# required directory | kafka_conf
- name: required directory | kafka_conf
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - "{{ kafka_conf_required_directory }}"
  when: kafka_conf_required_directory is defined
